title: IMS Education Portal: Learn to Burn!
author: Michelle, the Cat Queen
email: awesomeness.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the IMS learning portal where you'll find education 
  topics that you need to become productive fast. Let's modernize 
  IMS together by using the latest tools for DevOps, AI, and more.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
